T_var:
  Topt: 18.0
  Hopt: 65.0
dht22:
  pin: 27
  read_interval: 600
  save: true
  saving_dir: /home/fishnplants/Desktop/data/TH/
log:
  directory: /home/fishnplants/Desktop/
  filename: FnP_AeroGreenHouse
  level: INFO
config_reload_interval: 4
gpio_pins:
- name: AEROPONICS
  pin: 19
  what_type: pump
  interval: 10
  on_time: 15
- name: IDROPONICS
  pin: 12
  what_type: pump
  interval: 29
  on_time: 65
- name: MOISTURE
  pin: 26
  what_type: sensor
ir_control:
  rx_pin : 20
  tx_pin : 21
  file_ac_name: /home/fishnplants/Desktop/ac_remote.json
  default_temp: 22    # Temperatura di default climatizzatore
  enabled: true
  time_max_on: 300 # Max on time for the Air conditioner
  control_time: 2 #minutes separation for the control
  T_max: 24.0
  H_max: 65.0
