T_var:
  Topt: 18.0
dht22:
  pin: 27
  read_interval: 600
  save: true
  saving_dir: /home/fishnplants/Desktop/data/TH/
log:
  directory: /home/fishnplants/Desktop/
  filename: FnP_AeroGreenHouse
  level: INFO
config_reload_interval: 4
gpio_pins:
- name: AEROPONICS
  pin: 19
  what_type: pump
  interval: 10
  on_time: 15
- name: IDROPONICS
  pin: 12
  what_type: pump
  interval: 29
  on_time: 65
- name: MOISTURE
  pin: 26
  what_type: sensor
